# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
#    param_fetcher_listener:  true
#    allowed_methods_listener:  true
#    routing_loader: true
#    view:
#        view_response_listener:  true
#    exception:
#        codes:
#            App\Exception\MyException: 403
#        messages:
#            App\Exception\MyException: Forbidden area.
  format_listener:
    rules:
      - { path: '^/', priorities: ['json'], fallback_format: json}
  body_listener: true
  exception:
    enabled: true
    exception_controller: 'fos_rest.exception.controller:showAction'
  param_fetcher_listener: true
  view:
    view_response_listener: 'force'
    formats:
      json: true
  routing_loader:
    default_format: json
    include_format: false
